app = "bencher-api-test"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "6s"

[build]
image = "registry.fly.io/bencher-api-test"

[[services]]
protocol = "tcp"
internal_port = 61016

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 1024
soft_limit = 1024

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
