[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"
xtask-api = "run --manifest-path ./xtask/Cargo.toml --features api --"
xtask-cli = "run --manifest-path ./xtask/Cargo.toml --features cli --"
xtypes = "run --manifest-path ./xtask/Cargo.toml --features api -- types"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
